POST http://localhost:3000/category
Content-Type: application/json

{
    "name":"fashion"
}

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "firstName": "Chdloe",
  "lastName": "Bdarley",
  "email": "chloebdaxrley@example.com",
  "password": "secdurse@Password123"
}

POST http://localhost:3000/auth/login
Content-Type: application/json
{
    "email": "chloebdaxrley@example.com",
  "password": "secdurse@Password123"
}

{{
    const date = new Date()
    exports.startDate = date.toString()
    exports.endDate = date.toString()
}}

GET http://localhost:3000/products
?startDate={{ startDate }}
&endDate={{ endDate }}
&limit=5
&page=1



GET  http://localhost:3000/posts?id=15


POST http://localhost:3000/paystack/initialize
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjQsImVtYWlsIjoiY2hsb2ViZGF4cmxleUBleGFtcGxlLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc0MDQwMzc1MCwiZXhwIjoxNzQwNDA3MzUwfQ.gLjsX0axNc0yIRl6WYvIbwDwn3ghTC-RphbEb_pQgBo
Content-Type: application/json

{
  "email": "chloebdaxrley@example.com",
  "amount": 7000
}

POST http://localhost:3000/paystack/verify/2belnolr9r
Content-Type: application/json




